// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddSessionButton: typeof import('./src/components/AddSessionButton.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    Headers: typeof import('./src/components/Headers.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    OngoingSession: typeof import('./src/components/OngoingSession.vue')['default']
    OptionsMenu: typeof import('./src/components/OptionsMenu.vue')['default']
    RefreshButton: typeof import('./src/components/RefreshButton.vue')['default']
    Security: typeof import('./src/components/Security.vue')['default']
    Session: typeof import('./src/components/Session.vue')['default']
    Sessions: typeof import('./src/components/Sessions.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}

export {}
